### ISSUE TITLE
No finaliza ejecución de download_and_preprocess

### ISSUE THREAD

**Issue by leoguga** [UCA-Datalab/covid_occupancy_simulation#10]
El siguiente código se queda pillado a mitad de ejecución entre Córdoba y la siguiente provincia:
from web.background import check_new_url, download_and_preprocess
update = check_new_url(path_output_folder)
if update:
    download_and_preprocess(path_output_folder)

**Comment by daniprec** [comment]
He realizado un apaño temporal.

El código funciona correctamente mientras itera por las regiones presentes en la base de datos, pero falla al llegar a "españa". Al quitarla de la lista, el código ejecuta entero en pocos segundos. Como estamos estudiando los datos a nivel provincial, la región "españa" no nos interesa y por tanto no hay pérdida de información al ignorarla.

No tengo claro por qué falla "españa". Puede que el elevado número de pacientes, al tratarse del país entero y no una sóla provincia, sature la memoria del sistema. Habrá que investigarlo si queremos aplicar nuestro código a regiones mayores en el futuro.
